import Head from "next/head";
import { Container } from "@nextui-org/react";
import Login from "@/components/Login";

export default function SignIn() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by E-Portfolio" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        display="flex"
        justify="center"
        css={{ my: "$20", mw: "600px" }}
      >
        <Login />
      </Container>
    </>
  );
}