import Head from "next/head";
import { Container, Card, Row, Text } from "@nextui-org/react";
import Register from "@/components/Register";

export default function register() {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by E-Portfolio" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container justify="center" css={{ my: "$10", mw: "650px" }}>
        <Register />
      </Container>
    </>
  );
}
