import React, { useState } from "react";
import { axios } from "@/src/services";
import Loading from "@/src/components/Loading";
import Portfolio from "@/src/components/Portfolio";
import Head from "next/head";

export default function ViewCase() {
  const [isLoaded, setLoaded] = useState(false),
    [data, setData] = useState<any>([]);

  if (!isLoaded) {
    if (data.length === 0) {
      axios.get("/viewPrint").then(({ data }) => {
        setLoaded(true);
        setData(data);
      });
    }
  }
  return (
    <>
      <Head>
        <title>E-Portfolio</title>
        <meta name="description" content="Generated by E-Portfolio" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoaded ? <Portfolio data={data} /> : <Loading color={"primary"} />}
    </>
  );
}
