import Pending from "@/src/components/Admin/Accounts/Pending";
import { Container, Text } from "@nextui-org/react";
import Head from "next/head";

export default function PendingAccounts() {
  return (
    <>
      <Head>
        <title>E-Portfolio</title>
        <meta name="description" content="Generated by E-Portfolio" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container css={{ maxW: "1350px" }}>
        <Text
          size={24}
          weight="bold"
          css={{
            textAlign: "center",
            my: "$13",
          }}
        >
          Pending Accounts
        </Text>
        <Pending />
      </Container>
    </>
  );
}
